### PR TITLE
DOC: Alignments & Phylogeny

### PR DESCRIPTION
**Pull request by mikerobeson**
This is a draft intended for the "official documentation" of the q2-phylogeny plugin. This is largely based on the content located in the [Q2-phylogeny: Community Tutorial](https://forum.qiime2.org/t/q2-phylogeny-community-tutorial/4455). 

This is my first time contribution to the documents, which is why this is a draft pull request. I am still figuring out the details for testing. :-)

-Mike

### CODE REVIEW

**Comment by mikerobeson** [comment]
I am not sure what this error actually means:

> ... align-phylo.rst:document isn't included in any toctree ...

Anything I should be annotating in another file?

On another note, how should I point to files that need to be used? For example, I currently point to the `rep-seqs.qza` file from [this](https://docs.qiime2.org/2019.7/data/tutorials/atacama-soils/) tutorial. But I assume there is a more dynamic or better way to refer to required files?

**Comment by thermokarst** [comment]
> Anything I should be annotating in another file?

Yep! Please add an entry to this file: https://github.com/qiime2/docs/blob/master/source/tutorials/index.rst

> On another note, how should I point to files that need to be used? For example, I currently point to the `rep-seqs.qza` file from [this](https://docs.qiime2.org/2019.7/data/tutorials/atacama-soils/) tutorial. But I assume there is a more dynamic or better way to refer to required files?

We can create new data.qiime2.org links as necessary, let's coordinate during PR review!

**Comment by mikerobeson** [comment]
Guess something is up again:

> CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/qiime2-staging/label/r2019.10/linux-64/q2-fragment-insertion-2019.10.0.dev0-py36_0.tar.bz2>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
The command "conda env create -q -n test-env --file qiime2-latest-py36-linux-conda.yml" failed and exited with 1 during .
Your build has been stopped.

**Comment by thermokarst** [comment]
Anaconda hiccup --- a rebuild cleared it up.

**Comment by thermokarst** [comment]
Hey @mikerobeson - I built this tutorial last night, it took almost 12 hours on my machine (I swapped out the atacama data for MP data). @ebolyen and I are trying to come up with some alternatives here, because anything over ~15-20 min is going to become a huge bottleneck for our build system.

Options include:

1. Replacing with a micro-sized dataset
2. Disabling execution of the commands (this would lose the "verification" checks we get, though)
3. Expose some new "dry-run" functionality, still exploring this idea.

Just wanted to let you know where we are at with this. We need to get things merged soon, we are going to kick of package building for 2019.10 on Thursday... You don't need to do anything at this point, just looping you in. Thanks!

**Comment by mikerobeson** [comment]
@thermokarst  @ebolyen Whoa really!?!? I apologize for not considering this. 🤦‍♂ 

I think a good and very small set of sequences we can use would be from the [vsearch clustering tutorial](https://docs.qiime2.org/2019.7/tutorials/otu-clustering/). There are only 20 sequences in the `rep-seqs-dn-99.qza`. This should be sufficient for purposes of the tutorial.

**Comment by thermokarst** [comment]
Oh great, I hadn't thought about that tutorial - I will check it out now! No worries on the build time, we will figure something out! Really the issue is on our end, our build system shouldn't be so dependent on these things, and is one of the significant motivating factors behind [Library](https://library.qiime2.org/about/).

**Comment by thermokarst** [comment]
Woot! The vsearch dataset was lightning fast, about 5 minutes!

**Comment by thermokarst** [comment]
Hmm, looks like the screenshot was truncated, sorry about that...

**Comment by mikerobeson** [comment]
Wow, that looks marvelous! I really like the nested outline at the top!

**Pull request merged**
