### PR TITLE
ENH: Protocols paper updates

### LINKED ISSUE #455: QIIME 2 Protocols Paper Additions
1. Include text on how to "reactivate" (reuse the current "activate"  section, just make it more clear that this is how to reactivate, too).
2. Include text detailing a general workflow for deciding what type of install to perform, for different OSes.
3. Emphasize the the miniconda/anaconda docs are the best place for help with installing conda
4. Include examples of installing miniconda for macos and linux.

### PR DESCRIPTION
**Pull request by thermokarst**
Fixes #455

### CODE REVIEW

**Comment by thermokarst** [comment]
Can you clarify, what is the "live doc"? I thought I already included these changes, where relevant, in the Google Doc you shared with me on Slack.

**Comment by thermokarst** [comment]
More detail: the "reactivation" section in this PR was pulled directly from the manuscript. The "recommendations" section was a side-note from the TODO document you shared, but as I understood that wasn't going to be added to the manuscript.

**Comment by mestaki** [comment]
Sorry if this got a little confusing, with so many versions floating around it was just a matter of time. :P 
Yes, the "live doc" is the version I shared on Slack and that you have been editing/commenting on. So that's good! I did notice the re-activation section was directly from there too, again, perfect! 

Regarding the different OS and Miniconda installs: 1 of 2 things needed to happen to appease the reviewer's concern which was mainly about insufficient instruction: 1) We make our install recommendations all on the official Qiime2 documentations, so when the protocol paper points there, there is more details. Or 2) We provide example information right in the protocol paper.
Currently I think we've got a hybrid going on where I've added some extra info in the manuscript, and we have plans to add more info on the official Qiime2 docs. I propose just sticking to option 1. This would mean not making the changes proposed here (about the OS installs) to the RST version, but instead pushing those changes to the official q2 docs page for the next release. I can then reference that PR in our response letter, so the reviewer sees we've made the changes. I'll also go and delete the extra few sentences I wrote in the live doc. Does this make sense? Sorry again about the confusion.

**Comment by thermokarst** [comment]
No worries, @mestaki - glad I checked, I thought the "live version" == rst document!

> Does this make sense?

I think so - although I'm not really sure what you want me to do (it sounds like you already have or will be making the edits to the manuscript) - I'll just standby and wait for more guidance, that way I don't make any conflicting edits. Whatever you need, just let me know!

**Comment by mestaki** [comment]
I just had the very shameful realization that this PR was for changes to the 2020.5 official docs and NOT the QIIME 2 protocols paper. So please ignore my comments above! These changes all look good, and don't need to be ported to the Protocols Paper. Sorry about the confusion again there! I should read things more carefully :S

**Comment by thermokarst** [comment]
@nbokulich, are you available to give the text a read-through? If so, please assign to yourself. Thanks!

**Comment by nbokulich** [comment]
LGTM, thanks @thermokarst !

**Pull request merged**
