### PR TITLE
Sample language for artifact inspection info in concepts

### PR DESCRIPTION
**Pull request by kastman**
Hi all,

I'm not sure if this practical info about ``qiime tools view`` really belongs in the "Concepts" page in your view, but at least for a naive user trying to figure out what in the world to do to get "into" the visualizations I thought that providing a concrete example here might be helpful. 

For example, I had to dig into the Note that's 1/3 of the way down the moving pictures tutorial before I even found the view command, and was so confused by it opening in the browser that I instinctively cmd-w closed it without even letting it open the first time, so all I saw was a server with no front end view. 

Feel free to edit the text in this PR however you see fit, but it was a first pass from a totally new (to q2) user perspective. Thanks,

### CODE REVIEW

**Comment by thermokarst** [comment]
Thanks @kastman, one of will take a look at this soon, stay tuned!

Cross-referencing Issue #271.

**Comment by kastman** [comment]
Whelp! I didn't even test the artifacts until after I pushed this, but it appears that ``qiime tools view`` is _only_ for visualizations? Huh? So how does view.qiime2.org display artifacts? And how do I see, say, the equivalent of `cat sample.fastq | head`? The moving pictures tutorial has "view" links for a bunch of artifacts, but it's literally only metadata. Sorry, I didn't intend this PR to turn into a help Q&A, but maybe it will be useful for UX expectations?

**Comment by kastman** [comment]
Thanks @thermokarst for the issue ref; unless there's momentum I would certainly vote to collapse ``peek`` and ``view``.

**Comment by thermokarst** [comment]
> Sorry, I didn't intend this PR to turn into a help Q&A, but maybe it will be useful for UX expectations?

@kastman, these would be great questions to ask over on [Developer discussion on the forum](https://forum.qiime2.org/c/dev-discussion)! You can use your Github account to authenticate over there, so please re-post these questions over there.

> unless there's momentum I would certainly vote to collapse peek and view.

Lets discuss on the forum.

Thanks!

**Comment by kastman** [comment]
New discussion started on the forum: https://forum.qiime2.org/t/new-user-ux-for-viewing-artifacts-and-visualizations/3724

**Comment by thermokarst** [comment]
Hey @kastman - was looking through this thread again, wasn't sure if you were planning on working on this still or not (sorry this fell off the radar). If you are interested in a review of this PR please just let us know, otherwise feel free to close. Thanks!

**Comment by kastman** [comment]
Hey @thermokarst  - Thanks for the ping! My head is pretty far away from this right now unfortunately, so I'm going to close the issue, unless you want to accept the updated paragraph that's already in the PR or have suggestions on it. Sorry to drop this and leave the issue hanging!

**Comment by ebolyen** [comment]
No worries @kastman, thanks for the update!

**Pull request closed without merging**
