### PR TITLE
Fmt cdiff khanna

### PR DESCRIPTION
**Pull request by antgonza**
This is the new FMT C. Diff tutorial using the Khanna dataset. This is based on the [previous version](https://github.com/qiime2/docs/pull/353) just adapting the text and commands to this new dataset. 

Note that it uses SEPP and that the commands are slower than the old version.

cc: @ElDeveloper, @thermokarst

### CODE REVIEW

**Comment by thermokarst** [comment]
@antgonza - where should I get the sample metadata from? This tutorial won't build until the MD is in place. Just send me a TSV if you have a new file, otherwise, please point me in the right direction.

cc @ElDeveloper

**Comment by thermokarst** [comment]
Nevermind! I found it! Forgot we had a google drive folder with all this stuff in it. Stay tuned!

**Comment by lizgehret** [comment]
Hey @gregcaporaso @ebolyen looks like we never ended up adding this tutorial - should I just close this PR?

**Comment by gregcaporaso** [comment]
Yes, we can close this. IIRC, this was an early draft of what became the [_Current protocols_](https://currentprotocols.onlinelibrary.wiley.com/doi/10.1002/cpbi.100) paper, the content of which can also be found [here](https://curr-protoc-bioinformatics.qiime2.org/).

**Pull request closed without merging**
