### PR TITLE
BUG: correct deblur doc

### PR DESCRIPTION
**Pull request by RNAer**
@wasade , this is it, right?

### CODE REVIEW

**Comment by wasade** [comment]
Would it be possible to add an entry linking to the resulting `.qzv` and a light description of what is contained in there?

**Comment by RNAer** [comment]
Just looked at it - I can't find in the rst source file the section of `output` rendered in html page. It seems programmatically generated?

**Comment by jairideout** [comment]
[Check out the readme](https://github.com/qiime2/docs#contributing-to-the-docs), it describes the build targets. You can run `make html` to have the commands executed during build, which generates the `.qza`/`.qzv` files.

You'll probably want to add a command for generating a visualization of the deblur stats (I think that's what @wasade is asking for). This text should also get updated:

image

**Comment by jairideout** [comment]
@RNAer or @wasade any progress on this?

**Pull request merged**
